<?php
/**
 * Download exporter test double.
 *
 * @package ODSiteCheck
 */

/**
 * Captures real exporter output without terminating the PHPUnit process.
 */
final class ODSC_Test_Exporter extends ODSC_Exporter {
	/**
	 * Download-specific headers generated by the exporter.
	 *
	 * @var string[]
	 */
	public $download_headers = array();

	/**
	 * Captures download-specific headers.
	 *
	 * @param string[] $headers Header lines.
	 * @return void
	 */
	protected function send_download_headers( $headers ) {
		$this->download_headers = $headers;
	}

	/**
	 * Replaces exit so the test can inspect the completed response.
	 *
	 * @return void
	 * @throws ODSC_Test_Download_Completed Always signals normal completion.
	 */
	protected function terminate_download() {
		throw new ODSC_Test_Download_Completed();
	}
}
